version: "3.9"
services:
  api:
    image: api
    ports: 
      - "5000:5000"
  front:
    image: front
    ports:
      - "80:80"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

